version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: macros-count-app

